version: "3"
services:
  server:
    build: ./server
    restart: always
    ports:
      - "8081:8081"
      - "8082:8082"
    depends_on:
      - redis
      - postgres
    
  postgres:
    build: ./datastore/postgres
    volumes:
      - ./datastore/postgres/volume:/var/lib/postgresql/data
      - ./datastore/postgres/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: rest_user
      POSTGRES_PASSWORD: rest_password
      POSTGRES_DB: rest_db
    ports:
      - '5432:5432'

  redis:
    image: redis:6.0.8-alpine